/* ------------------------------------------------------------------ *
 * _data.js — simulated placeholder data.
 *
 * EVERYTHING IN THIS FILE IS FAKE. It is generated by a seeded PRNG so
 * that it is deterministic across reloads, organically noisy rather than
 * obviously synthetic, and shaped to exercise every figure on the site.
 *
 * When real results arrive, replace the functions in SITE.data — the
 * return shapes are documented above each one and nothing else changes.
 * ------------------------------------------------------------------ */
window.SITE = window.SITE || {};

SITE.gen = (function () {
  'use strict';

  function hash(str) {
    var h = 2166136261 >>> 0;
    for (var i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619); }
    return h >>> 0;
  }

  // mulberry32
  function rng(seed) {
    var a = (typeof seed === 'string' ? hash(seed) : seed) >>> 0;
    return function () {
      a |= 0; a = (a + 0x6D2B79F5) | 0;
      var t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  function gauss(r) {
    var u = 0, v = 0;
    while (u === 0) u = r();
    while (v === 0) v = r();
    return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
  }

  /* Mean-reverting random walk — looks like a real measured series. */
  function walk(n, opts) {
    opts = opts || {};
    var r = rng(opts.seed || 'walk');
    var x = opts.start != null ? opts.start : 0;
    var mean = opts.mean != null ? opts.mean : x;
    var vol = opts.vol != null ? opts.vol : 0.05;
    var pull = opts.pull != null ? opts.pull : 0.08;
    var drift = opts.drift || 0;
    var out = [];
    for (var i = 0; i < n; i++) {
      x += drift + pull * (mean - x) + vol * gauss(r);
      if (opts.min != null) x = Math.max(opts.min, x);
      if (opts.max != null) x = Math.min(opts.max, x);
      out.push(x);
    }
    return out;
  }

  function smooth(arr, k) {
    k = k || 2;
    return arr.map(function (_, i) {
      var lo = Math.max(0, i - k), hi = Math.min(arr.length - 1, i + k), s = 0, n = 0;
      for (var j = lo; j <= hi; j++) { s += arr[j]; n++; }
      return s / n;
    });
  }

  /* Gaussian bump — used for campaign events (a debate, a scandal). */
  function bump(n, centre, width, height) {
    var out = [];
    for (var i = 0; i < n; i++) out.push(height * Math.exp(-Math.pow((i - centre) / width, 2)));
    return out;
  }

  function normaliseRows(rows) {
    return rows.map(function (row) {
      var s = row.reduce(function (a, b) { return a + b; }, 0) || 1;
      return row.map(function (v) { return v / s; });
    });
  }

  function round(x, d) { var m = Math.pow(10, d == null ? 2 : d); return Math.round(x * m) / m; }
  function clamp(x, a, b) { return Math.max(a, Math.min(b, x)); }
  function range(n) { var o = []; for (var i = 0; i < n; i++) o.push(i); return o; }
  function sum(a) { return a.reduce(function (x, y) { return x + y; }, 0); }
  function mean(a) { return sum(a) / a.length; }

  return { hash: hash, rng: rng, gauss: gauss, walk: walk, smooth: smooth, bump: bump,
           normaliseRows: normaliseRows, round: round, clamp: clamp, range: range,
           sum: sum, mean: mean };
}());


SITE.data = (function () {
  'use strict';

  var E = SITE.entities;
  var G = SITE.gen;
  var DAYS = 41;
  var cache = {};

  function memo(key, fn) {
    if (!(key in cache)) cache[key] = fn();
    return cache[key];
  }

  /* ================================================================
   * RQ1 — visibility & polarisation
   * ================================================================ */

  /* Actor share of mentions, by day, optionally filtered to one source.
   * → { days:[{i,label}], series:[{id,name,short,slot,values:[0..1]}] } */
  function visibility(eventId, sourceId) {
    return memo('vis:' + eventId + ':' + (sourceId || 'all'), function () {
      var ev = E.events[eventId];
      var actors = ev.actors.slice(0, eventId === 'qc' ? 5 : 4);
      // Baseline attention, before any newsroom's own preferences.
      var base = eventId === 'qc'
        ? { cn: 0.32, pld: 0.26, ms: 0.19, av: 0.12, pr: 0.11 }
        : { no: 0.34, yes: 0.33, ewu: 0.18, tvc: 0.15 };

      // Each newsroom over- or under-weights particular actors. Fixed, not random,
      // because the story in Route 1A depends on these specific tilts.
      var tilts = {
        all:       {},
        boreal:    { ms: 1.22, av: 1.30, tvc: 1.45, pr: 0.82 },
        depeche:   { cn: 1.10, pld: 1.14, ms: 0.90, av: 0.78 },
        herald:    { no: 1.12, yes: 0.95, mt: 1.20 },
        matin:     { cn: 1.24, pr: 1.28, ms: 0.66, av: 0.55, tvc: 0.60 },
        foothills: { yes: 1.26, ewu: 1.30, tvc: 0.58, no: 0.88 },
        westwire:  { ms: 1.18, av: 1.12, yes: 1.08 },
        fil:       { cn: 1.02, no: 1.02 },
        signal:    { pr: 1.62, cn: 1.10, ms: 0.52, av: 0.44, yes: 1.40, tvc: 0.42 }
      };
      var tilt = tilts[sourceId || 'all'] || {};

      // Campaign beats, shared by every source (the news cycle is common).
      var beats = {
        launch:  G.bump(DAYS, 8, 3.0, 0.55),   // one party's platform launch
        storm:   G.bump(DAYS, 17, 2.4, 0.70),  // a controversy
        debate:  G.bump(DAYS, 23, 2.0, 0.60),  // the leaders' debate
        endgame: G.range(DAYS).map(function (i) { return i < 33 ? 0 : (i - 32) / 8 * 0.65; })
      };
      var beatMap = eventId === 'qc'
        ? { cn: ['debate', 'endgame'], pld: ['storm', 'debate', 'endgame'], ms: ['launch'], av: ['launch'], pr: [] }
        : { no: ['debate', 'endgame'], yes: ['storm', 'debate', 'endgame'], ewu: ['launch'], tvc: [] };

      var rows = G.range(DAYS).map(function (i) {
        return actors.map(function (a) {
          var r = G.rng('vis' + eventId + (sourceId || 'all') + a.id + i);
          var v = base[a.id] * (tilt[a.id] || 1);
          (beatMap[a.id] || []).forEach(function (b) { v *= (1 + beats[b][i]); });
          // Tail actors lose ground in the last week everywhere.
          if (!(beatMap[a.id] || []).length && i > 32) v *= 1 - (i - 32) * 0.035;
          return Math.max(0.01, v * (1 + 0.16 * (r() - 0.5)));
        });
      });
      rows = G.normaliseRows(rows);

      return {
        days: G.range(DAYS).map(function (i) { return { i: i, label: E.dayLabel(i) }; }),
        series: actors.map(function (a, k) {
          return {
            id: a.id, name: a.name, short: a.short, slot: a.slot,
            values: G.smooth(rows.map(function (row) { return row[k]; }), 1).map(function (v) { return G.round(v, 4); })
          };
        })
      };
    });
  }

  /* Final-week ranking for one source. → [{id,name,value,slot}] */
  function finalWeek(eventId, sourceId) {
    var v = visibility(eventId, sourceId);
    return v.series.map(function (s) {
      return { id: s.id, name: s.short, full: s.name, slot: s.slot,
               value: G.round(G.mean(s.values.slice(34)) * 100, 1) };
    }).sort(function (a, b) { return b.value - a.value; });
  }

  /* Visibility × polarisation map. Hand-set so the quadrants tell a story.
   * → [{id,label,kind,x,y,n}]  x = % of all mentions, y = cross-source stance SD */
  function polarisationMap(eventId) {
    var qc = [
      { id: 'cn',      label: 'Coalition Nationale',  kind: 'Actor', x: 21.4, y: 0.34 },
      { id: 'pld',     label: 'Parti Libéral-Démocrate', kind: 'Actor', x: 17.8, y: 0.29 },
      { id: 'ms',      label: 'Mouvement Solidaire',  kind: 'Actor', x: 12.1, y: 0.51 },
      { id: 'av',      label: 'Alliance Verte',       kind: 'Actor', x: 6.9,  y: 0.22 },
      { id: 'pr',      label: 'Parti de la Relance',  kind: 'Actor', x: 5.4,  y: 0.58 },
      { id: 'cost',    label: 'Cost of living',       kind: 'Issue', x: 14.2, y: 0.14 },
      { id: 'health',  label: 'Health care',          kind: 'Issue', x: 11.6, y: 0.17 },
      { id: 'imm',     label: 'Immigration & language', kind: 'Issue', x: 9.8, y: 0.61 },
      { id: 'ident',   label: 'Secularism & identity', kind: 'Issue', x: 7.2, y: 0.66 },
      { id: 'climate', label: 'Climate & energy',     kind: 'Issue', x: 6.1,  y: 0.44 },
      { id: 'housing', label: 'Housing',              kind: 'Issue', x: 5.3,  y: 0.19 },
      { id: 'educ',    label: 'Education',            kind: 'Issue', x: 3.4,  y: 0.24 },
      { id: 'p_tax',   label: '“Cut the payroll tax”', kind: 'Position', x: 2.8, y: 0.47 },
      { id: 'p_quota', label: '“Cap newcomer intake”', kind: 'Position', x: 3.6, y: 0.72 },
      { id: 'p_rent',  label: '“Freeze rents”',        kind: 'Position', x: 2.1, y: 0.53 },
      { id: 'p_nurse', label: '“Hire 4,000 nurses”',   kind: 'Position', x: 2.4, y: 0.12 }
    ];
    var ab = [
      { id: 'no',     label: 'One Canada Alberta',    kind: 'Actor', x: 19.7, y: 0.38 },
      { id: 'yes',    label: 'Alberta Forward',       kind: 'Actor', x: 22.9, y: 0.47 },
      { id: 'ewu',    label: 'Energy Workers United', kind: 'Actor', x: 8.4,  y: 0.55 },
      { id: 'tvc',    label: 'Treaty Voices Coalition', kind: 'Actor', x: 4.1, y: 0.31 },
      { id: 'sov',    label: 'Sovereignty & constitution', kind: 'Issue', x: 18.2, y: 0.69 },
      { id: 'energy', label: 'Energy & pipelines',    kind: 'Issue', x: 12.8, y: 0.42 },
      { id: 'fiscal', label: 'Equalisation & fiscal', kind: 'Issue', x: 10.4, y: 0.35 },
      { id: 'treaty', label: 'Treaty & Indigenous rights', kind: 'Issue', x: 5.2, y: 0.28 },
      { id: 'fed',    label: 'Federal relations',     kind: 'Issue', x: 9.1,  y: 0.58 },
      { id: 'econ',   label: 'Economy & jobs',        kind: 'Issue', x: 7.6,  y: 0.21 },
      { id: 'cost',   label: 'Cost of living',        kind: 'Issue', x: 6.2,  y: 0.13 },
      { id: 'p_pen',  label: '“Provincial pension plan”', kind: 'Position', x: 4.4, y: 0.64 },
      { id: 'p_con',  label: '“Constitutional talks first”', kind: 'Position', x: 3.1, y: 0.40 },
      { id: 'p_stay', label: '“Stay in the federation”', kind: 'Position', x: 5.8, y: 0.33 }
    ];
    var rows = eventId === 'qc' ? qc : ab;
    return rows.map(function (d) {
      var r = G.rng('pm' + eventId + d.id);
      return Object.assign({}, d, { n: Math.round(400 + d.x * 180 * (0.8 + 0.4 * r())) });
    });
  }

  /* Coverage share vs population share, by social group.
   * → [{id,name,coverage,population,quoted}] (all 0-1) */
  function groupGap(eventId) {
    var lean = eventId === 'qc'
      ? { young: 0.52, senior: 1.34, newcom: 0.71, indig: 0.44, rural: 1.18, renters: 0.49, workers: 0.96, lowinc: 0.42, ling: 1.62 }
      : { young: 0.48, senior: 1.28, newcom: 0.55, indig: 0.88, rural: 1.46, renters: 0.38, workers: 1.94, lowinc: 0.40, ling: 0.61 };
    return E.groups.map(function (g) {
      var r = G.rng('gg' + eventId + g.id);
      var cov = G.clamp(g.pop * lean[g.id] * (0.94 + 0.12 * r()), 0.01, 0.6);
      return {
        id: g.id, name: g.name,
        population: g.pop,
        coverage: G.round(cov, 4),
        // Share of those mentions where a member of the group is quoted directly.
        quoted: G.round(cov * (0.24 + 0.34 * r()), 4)
      };
    }).sort(function (a, b) { return (b.coverage - b.population) - (a.coverage - a.population); });
  }

  /* ================================================================
   * RQ2 — linguistic and visual framing
   * ================================================================ */

  /* One news event, seven newsrooms' headlines, bias spans marked up.
   * → [{id,label,facts,headlines:[{source,text,spans:[{t,dim,note}]}]}] */
  function headlineSets() {
    return [
      {
        id: 'debate',
        label: 'The leaders’ debate — Quebec, day 23',
        facts: 'A 120-minute televised debate between five party leaders. Exchanges on health-care wait times, immigration levels and the payroll tax. No new policy was announced.',
        headlines: [
          { source: 'fil', text: 'Five leaders debate health care, immigration and taxes', spans: [] },
          { source: 'boreal', text: 'Leaders spar over wait times as immigration dominates second hour',
            spans: [{ t: 'spar', dim: 'metaph', note: 'Conflict metaphor: a debate rendered as combat.' },
                    { t: 'dominates', dim: 'inten', note: 'Intensifier on the volume of one topic.' }] },
          { source: 'depeche', text: 'Marchand defends her record as Roy presses on hospital delays',
            spans: [{ t: 'defends', dim: 'epi', note: 'Positions one actor as answering, the other as asking.' },
                    { t: 'presses', dim: 'epi', note: 'Assigns initiative to the challenger.' }] },
          { source: 'matin', text: 'Ouellet claims her plan is funded — rivals aren’t buying it',
            spans: [{ t: 'claims', dim: 'epi', note: '“Claims” withholds endorsement in a way “says” does not.' },
                    { t: 'aren’t buying it', dim: 'dist', note: 'Colloquial distancing from the claim.' }] },
          { source: 'westwire', text: 'The debate’s real winner was the payroll tax question',
            spans: [{ t: 'real winner', dim: 'metaph', note: 'Sport frame; also an evaluative judgement in the headline.' }] },
          { source: 'signal', text: 'Radical spending plan goes unchallenged in tepid debate',
            spans: [{ t: 'Radical', dim: 'inten', note: 'One-sided intensifier attached to a single party.' },
                    { t: 'unchallenged', dim: 'agency', note: 'Agency deleted: by whom?' },
                    { t: 'tepid', dim: 'inten', note: 'Evaluative framing of the event itself.' }] },
          { source: 'herald', text: 'Quebec leaders clash; Alberta’s question barely came up',
            spans: [{ t: 'clash', dim: 'metaph', note: 'Conflict metaphor.' },
                    { t: 'barely', dim: 'inten', note: 'Intensifier of absence.' }] }
        ]
      },
      {
        id: 'ruling',
        label: 'The constitutional opinion — Alberta, day 17',
        facts: 'A provincial court of appeal released a 60-page reference opinion on the referendum question’s wording. The opinion found the wording lawful and declined to rule on the consequences of a Yes result.',
        headlines: [
          { source: 'fil', text: 'Court finds referendum wording lawful, declines to rule on effect', spans: [] },
          { source: 'herald', text: 'Court clears referendum question but leaves the hard part unanswered',
            spans: [{ t: 'clears', dim: 'epi', note: 'Endorsing verb; the opinion “found”, it did not “clear”.' },
                    { t: 'the hard part', dim: 'inten', note: 'Evaluative characterisation of what was left open.' }] },
          { source: 'foothills', text: 'Judges refuse to say what a Yes vote would actually do',
            spans: [{ t: 'refuse', dim: 'epi', note: '“Refuse” implies unwillingness; the opinion said it was not properly before the court.' },
                    { t: 'actually', dim: 'dist', note: 'Distancing: implies previous accounts were not real.' }] },
          { source: 'boreal', text: 'Reference opinion upholds wording; consequences left to the legislature',
            spans: [{ t: 'upholds', dim: 'epi', note: 'Mildly endorsing but accurate to the disposition.' }] },
          { source: 'signal', text: 'Another loss for the campaign to shut down Alberta’s vote',
            spans: [{ t: 'Another loss', dim: 'inten', note: 'Frames a legal finding as a running score.' },
                    { t: 'shut down', dim: 'metaph', note: 'Characterises one side’s aim in conflict terms.' }] },
          { source: 'westwire', text: 'What the court did and didn’t decide, in six paragraphs', spans: [] },
          { source: 'matin', text: 'Feu vert pour la question albertaine, flou sur la suite',
            spans: [{ t: 'Feu vert', dim: 'metaph', note: 'Traffic-light metaphor implying approval rather than a finding.' },
                    { t: 'flou', dim: 'inten', note: 'Characterises the opinion as vague.' }] }
        ]
      },
      {
        id: 'costing',
        label: 'The costing release — Quebec, day 31',
        facts: 'The independent budget office published costings of four parties’ platforms. Two were within their own published estimates, two exceeded them by more than 8%.',
        headlines: [
          { source: 'fil', text: 'Budget office costs four platforms; two exceed party estimates', spans: [] },
          { source: 'depeche', text: 'Two platforms blow past their own numbers',
            spans: [{ t: 'blow past', dim: 'metaph', note: 'Force metaphor for an accounting variance.' }] },
          { source: 'matin', text: 'Solidaire plan costs billions more than promised',
            spans: [{ t: 'billions more', dim: 'inten', note: 'Absolute framing of a proportional gap; the other over-estimate is not named.' }] },
          { source: 'boreal', text: 'Costings land: gaps on both sides of the spending debate', spans: [] },
          { source: 'signal', text: 'The numbers nobody on the left wants to talk about',
            spans: [{ t: 'nobody on the left', dim: 'dist', note: 'Group attribution without a named source.' },
                    { t: 'wants to talk about', dim: 'agency', note: 'Motive attributed without evidence.' }] },
          { source: 'westwire', text: 'We put the four costings side by side. Here’s the gap.', spans: [] },
          { source: 'herald', text: 'Quebec costings show a pattern Alberta’s camps have avoided',
            spans: [{ t: 'avoided', dim: 'epi', note: 'Attributes intent to an absence.' }] }
        ]
      }
    ];
  }

  /* Source × bias-dimension matrix, standardised (0 = corpus mean, in SDs).
   * → { rows:[sourceId], cols:[dimId], cells:[{row,col,value,n}] } */
  function biasHeat(eventId) {
    return memo('bias:' + eventId, function () {
      // Deliberate signatures: tabloids high on intensifiers and metaphor, the
      // wire near zero everywhere, the partisan outlet high on distancing.
      var profile = {
        boreal:    { epi: -0.28, inten: -0.35, attrib: -0.42, agency: -0.10, dist: -0.30, metaph: 0.22 },
        depeche:   { epi: 0.12,  inten: 0.05,  attrib: 0.18,  agency: 0.24,  dist: -0.05, metaph: 0.35 },
        herald:    { epi: 0.05,  inten: -0.12, attrib: 0.22,  agency: 0.30,  dist: 0.02,  metaph: 0.28 },
        matin:     { epi: 0.62,  inten: 0.94,  attrib: 0.58,  agency: 0.36,  dist: 0.55,  metaph: 1.05 },
        foothills: { epi: 0.55,  inten: 0.88,  attrib: 0.44,  agency: 0.41,  dist: 0.48,  metaph: 0.96 },
        westwire:  { epi: -0.15, inten: 0.30,  attrib: -0.26, agency: -0.32, dist: 0.10,  metaph: 0.05 },
        fil:       { epi: -0.52, inten: -0.61, attrib: -0.55, agency: -0.18, dist: -0.58, metaph: -0.48 },
        signal:    { epi: 0.88,  inten: 1.12,  attrib: 0.96,  agency: 0.72,  dist: 1.28,  metaph: 0.84 }
      };
      var shift = eventId === 'ab' ? 0.12 : 0;
      var cells = [];
      E.sources.forEach(function (s) {
        E.biasDims.forEach(function (d) {
          var r = G.rng('bh' + eventId + s.id + d.id);
          cells.push({
            row: s.id, col: d.id,
            value: G.round(profile[s.id][d.id] + shift * (d.id === 'metaph' ? 1 : 0.3) + 0.10 * G.gauss(r), 2),
            n: Math.round(600 + 2400 * r())
          });
        });
      });
      return {
        rows: E.sources.map(function (s) { return { id: s.id, label: s.name, meta: s.kind }; }),
        cols: E.biasDims.map(function (d) { return { id: d.id, label: d.name, gloss: d.gloss }; }),
        cells: cells
      };
    });
  }

  /* Coded press photographs. → [{id,actor,source,angle,shot,expr,set,congruence}] */
  function imageCodes() {
    return memo('img', function () {
      var out = [];
      var actors = [{ id: 'cn', label: 'Marchand (CN)' }, { id: 'ms', label: 'Ouellet (MS)' },
                    { id: 'yes', label: 'Yes camp' }, { id: 'no', label: 'No camp' }];
      var srcs = ['boreal', 'depeche', 'matin', 'foothills', 'westwire', 'signal'];
      // Favourability tilt per (source, actor): drives angle/expression choices.
      var fav = {
        boreal:    { cn: 0.02, ms: 0.10, yes: -0.04, no: 0.04 },
        depeche:   { cn: 0.22, ms: -0.18, yes: -0.10, no: 0.14 },
        matin:     { cn: 0.34, ms: -0.44, yes: 0.06, no: -0.02 },
        foothills: { cn: 0.04, ms: -0.20, yes: 0.46, no: -0.32 },
        westwire:  { cn: -0.06, ms: 0.14, yes: 0.08, no: 0.02 },
        signal:    { cn: 0.30, ms: -0.62, yes: 0.58, no: -0.40 }
      };
      srcs.forEach(function (s) {
        actors.forEach(function (a) {
          for (var k = 0; k < 3; k++) {
            var r = G.rng('im' + s + a.id + k);
            var f = fav[s][a.id] + 0.18 * G.gauss(r);
            out.push({
              id: s + '-' + a.id + '-' + k,
              source: s, actor: a.id, actorLabel: a.label,
              angle: f > 0.18 ? 'Low (looking up)' : f < -0.14 ? 'High (looking down)' : 'Eye level',
              shot: r() > 0.62 ? 'Close-up' : r() > 0.3 ? 'Medium' : 'Wide',
              expr: f > 0.12 ? 'Positive' : f < -0.12 ? 'Negative' : 'Neutral',
              set: ['Podium', 'Crowd', 'Candid', 'Institutional'][Math.floor(r() * 4)],
              favour: G.round(f, 2),
              // −1 caption contradicts the image, +1 caption reinforces it
              congruence: G.round(G.clamp(f * 0.8 + 0.3 * G.gauss(r), -1, 1), 2)
            });
          }
        });
      });
      return out;
    });
  }

  /* Image–caption relationship, as a diverging distribution per source.
   * → { categories:[...], rows:[{id,label,values:[...]}] } */
  function captionCongruence() {
    var imgs = imageCodes();
    var cats = ['Caption contradicts image', 'Caption is neutral', 'Caption reinforces image'];
    var by = {};
    imgs.forEach(function (d) {
      by[d.source] = by[d.source] || [0, 0, 0];
      by[d.source][d.congruence < -0.15 ? 0 : d.congruence > 0.15 ? 2 : 1]++;
    });
    return {
      categories: cats,
      centreIndex: 1,
      rows: Object.keys(by).map(function (s) {
        var t = G.sum(by[s]);
        return { id: s, label: E.sourceById[s].name, values: by[s].map(function (v) { return G.round(v / t, 3); }) };
      })
    };
  }

  /* ================================================================
   * RQ3 — messages from actors to coverage
   * ================================================================ */

  /* Three-stage flow with adjacent links only: every message issued by a
   * campaign goes down a channel, and is then either reported or not.
   * Ribbons keep the originating theme's colour across both hops.
   * → { stages, nodes:[{id,stage,label,value,slot}], links:[{source,target,value,slot}], legend } */
  function messageFlow(eventId) {
    return memo('flow:' + eventId, function () {
      var frames = eventId === 'qc'
        ? [{ id: 'cost', label: 'Cost of living', slot: 1 }, { id: 'health', label: 'Health care', slot: 2 },
           { id: 'imm', label: 'Immigration & language', slot: 3 }, { id: 'ident', label: 'Identity & secularism', slot: 4 },
           { id: 'climate', label: 'Climate & energy', slot: 5 }, { id: 'other', label: 'Everything else', slot: 7 }]
        : [{ id: 'sov', label: 'Sovereignty', slot: 1 }, { id: 'energy', label: 'Energy & pipelines', slot: 2 },
           { id: 'fiscal', label: 'Equalisation', slot: 3 }, { id: 'treaty', label: 'Treaty rights', slot: 4 },
           { id: 'health', label: 'Health care', slot: 5 }, { id: 'other', label: 'Everything else', slot: 7 }];

      var issued  = eventId === 'qc' ? [820, 640, 510, 300, 380, 700] : [910, 700, 560, 240, 330, 620];
      var adRate  = eventId === 'qc' ? [0.42, 0.30, 0.55, 0.61, 0.18, 0.12] : [0.58, 0.52, 0.47, 0.11, 0.21, 0.10];
      // Uptake is higher for ad-backed messages, but the gap varies by theme.
      var upPaid  = eventId === 'qc' ? [0.44, 0.52, 0.71, 0.78, 0.30, 0.22] : [0.74, 0.55, 0.49, 0.41, 0.34, 0.20];
      var upOrg   = eventId === 'qc' ? [0.25, 0.34, 0.47, 0.51, 0.16, 0.11] : [0.58, 0.36, 0.29, 0.22, 0.19, 0.09];

      var nodes = [], links = [];
      var tot = { paid: 0, organic: 0, reported: 0, unreported: 0 };

      frames.forEach(function (f, i) {
        var paid = Math.round(issued[i] * adRate[i]);
        var org = issued[i] - paid;
        var repP = Math.round(paid * upPaid[i]), repO = Math.round(org * upOrg[i]);

        nodes.push({ id: 'f-' + f.id, stage: 0, label: f.label, value: issued[i], slot: f.slot });
        links.push({ source: 'f-' + f.id, target: 'paid', value: paid, slot: f.slot, label: f.label });
        links.push({ source: 'f-' + f.id, target: 'organic', value: org, slot: f.slot, label: f.label });
        links.push({ source: 'paid', target: 'reported', value: repP, slot: f.slot, label: f.label });
        links.push({ source: 'paid', target: 'unreported', value: paid - repP, slot: f.slot, label: f.label });
        links.push({ source: 'organic', target: 'reported', value: repO, slot: f.slot, label: f.label });
        links.push({ source: 'organic', target: 'unreported', value: org - repO, slot: f.slot, label: f.label });

        tot.paid += paid; tot.organic += org;
        tot.reported += repP + repO; tot.unreported += (paid - repP) + (org - repO);
      });

      nodes.push({ id: 'paid', stage: 1, label: 'Backed by ad spend', value: tot.paid });
      nodes.push({ id: 'organic', stage: 1, label: 'Organic only', value: tot.organic });
      nodes.push({ id: 'reported', stage: 2, label: 'Reported in news', value: tot.reported });
      nodes.push({ id: 'unreported', stage: 2, label: 'Never reported', value: tot.unreported });

      return {
        stages: ['Messages issued', 'How they were pushed', 'What happened next'],
        nodes: nodes, links: links,
        legend: frames.map(function (f) { return { slot: f.slot, label: f.label }; }),
        totals: tot
      };
    });
  }

  /* Uptake rate per message frame. → [{id,label,value,spend,actor,slot}] */
  function uptake(eventId) {
    var qc = [
      { id: 'm1', label: '“Cap newcomer intake”',        actor: 'cn',  value: 0.71, spend: 0.18 },
      { id: 'm2', label: '“Emergency-room guarantee”',   actor: 'pld', value: 0.58, spend: 0.22 },
      { id: 'm3', label: '“Cut the payroll tax”',        actor: 'cn',  value: 0.44, spend: 0.26 },
      { id: 'm4', label: '“Freeze rents for three years”', actor: 'ms', value: 0.39, spend: 0.09 },
      { id: 'm5', label: '“Hire 4,000 nurses”',          actor: 'ms',  value: 0.31, spend: 0.11 },
      { id: 'm6', label: '“Public transit in every region”', actor: 'av', value: 0.18, spend: 0.06 },
      { id: 'm7', label: '“Balanced budget by 2029”',    actor: 'pr',  value: 0.16, spend: 0.19 },
      { id: 'm8', label: '“Climate adaptation fund”',    actor: 'av',  value: 0.11, spend: 0.08 },
      { id: 'm9', label: '“Daycare in every workplace”', actor: 'pld', value: 0.09, spend: 0.21 }
    ];
    var ab = [
      { id: 'n1', label: '“Alberta’s fair share”',       actor: 'yes', value: 0.78, spend: 0.31 },
      { id: 'n2', label: '“A vote changes nothing overnight”', actor: 'no', value: 0.62, spend: 0.19 },
      { id: 'n3', label: '“Provincial pension plan”',    actor: 'yes', value: 0.55, spend: 0.24 },
      { id: 'n4', label: '“Pipelines need Ottawa”',      actor: 'no',  value: 0.41, spend: 0.16 },
      { id: 'n5', label: '“Energy jobs at stake”',       actor: 'ewu', value: 0.37, spend: 0.28 },
      { id: 'n6', label: '“Treaties are not a provincial matter”', actor: 'tvc', value: 0.22, spend: 0.04 },
      { id: 'n7', label: '“Cities pay the bill”',        actor: 'mt',  value: 0.14, spend: 0.07 },
      { id: 'n8', label: '“No new taxes either way”',    actor: 'pta', value: 0.08, spend: 0.22 }
    ];
    var rows = (eventId === 'qc' ? qc : ab);
    return rows.map(function (d) {
      var a = E.actorById[d.actor];
      return Object.assign({}, d, { actorLabel: a ? a.short : d.actor, slot: a ? a.slot : 7 });
    });
  }

  /* How a claim's framing shifts between the actor's mouth and the news page.
   * → [{id,claim,actor,from,to,fromLabel,toLabel,dim}] on a −1…+1 scale */
  function framingShift(eventId) {
    var qc = [
      { id: 's1', claim: '“Cap newcomer intake”', actor: 'cn', dim: 'Presented as', from: 0.62, to: 0.18,
        fromLabel: 'capacity and services', toLabel: 'identity and language' },
      { id: 's2', claim: '“Freeze rents”', actor: 'ms', dim: 'Presented as', from: 0.55, to: -0.22,
        fromLabel: 'affordability', toLabel: 'cost to landlords' },
      { id: 's3', claim: '“Cut the payroll tax”', actor: 'cn', dim: 'Presented as', from: 0.48, to: 0.36,
        fromLabel: 'small business relief', toLabel: 'deficit risk' },
      { id: 's4', claim: '“Hire 4,000 nurses”', actor: 'ms', dim: 'Presented as', from: 0.51, to: 0.12,
        fromLabel: 'staffing shortfall', toLabel: 'costing dispute' },
      { id: 's5', claim: '“Balanced budget by 2029”', actor: 'pr', dim: 'Presented as', from: 0.40, to: 0.31,
        fromLabel: 'fiscal discipline', toLabel: 'service cuts' }
    ];
    var ab = [
      { id: 't1', claim: '“Alberta’s fair share”', actor: 'yes', dim: 'Presented as', from: 0.68, to: 0.24,
        fromLabel: 'fiscal fairness', toLabel: 'separation risk' },
      { id: 't2', claim: '“Provincial pension plan”', actor: 'yes', dim: 'Presented as', from: 0.59, to: 0.08,
        fromLabel: 'retirement returns', toLabel: 'transfer uncertainty' },
      { id: 't3', claim: '“Treaties are not a provincial matter”', actor: 'tvc', dim: 'Presented as', from: 0.64, to: 0.44,
        fromLabel: 'constitutional obligation', toLabel: 'legal obstacle' },
      { id: 't4', claim: '“Energy jobs at stake”', actor: 'ewu', dim: 'Presented as', from: 0.57, to: 0.49,
        fromLabel: 'employment', toLabel: 'employment' },
      { id: 't5', claim: '“A vote changes nothing overnight”', actor: 'no', dim: 'Presented as', from: 0.46, to: 0.21,
        fromLabel: 'legal process', toLabel: 'campaign tactic' }
    ];
    return (eventId === 'qc' ? qc : ab).map(function (d) {
      var a = E.actorById[d.actor];
      return Object.assign({}, d, { actorLabel: a ? a.short : d.actor, slot: a ? a.slot : 7 });
    });
  }

  /* ================================================================
   * RQ4 — social media amplification
   * ================================================================ */

  /* Accounts and outlets, linked by sharing. → { nodes:[...], links:[...] } */
  function ampNetwork() {
    return memo('net', function () {
      var nodes = [], links = [];
      // Three communities, deliberately: pro-Yes/right-leaning, pro-No/left-leaning, institutional.
      var comms = [
        { id: 'c1', label: 'Sovereignty-aligned cluster', slot: 2 },
        { id: 'c2', label: 'Federalist-aligned cluster', slot: 1 },
        { id: 'c3', label: 'Institutional & civic cluster', slot: 3 }
      ];
      E.sources.forEach(function (s) {
        var c = { boreal: 'c3', fil: 'c3', depeche: 'c3', herald: 'c3', westwire: 'c3',
                  matin: 'c1', foothills: 'c1', signal: 'c1' }[s.id];
        nodes.push({ id: 'src-' + s.id, label: s.short, type: 'outlet', comm: c, size: 26 });
      });
      var names = ['@prairie_watch', '@le_fil_rouge', '@AB_sovereignty', '@QC_verified', '@energy_first',
                   '@treaty_now', '@citycouncilAB', '@campaign_decoder', '@northwind', '@reveil_qc',
                   '@fact_check_ca', '@foothills_dad', '@laurentienne', '@pipeline_pete', '@la_releve',
                   '@calgary_renter', '@quebec_reader', '@westernvoice', '@solidarite_mtl', '@budgethawk',
                   '@boreal_listener', '@albertafirst_', '@montrealer_', '@ruralvoice_ab'];
      names.forEach(function (n, i) {
        var r = G.rng('acct' + n);
        var c = comms[i % 3].id;
        nodes.push({
          id: n, label: n, type: 'account', comm: c,
          size: 6 + Math.pow(r(), 2) * 26,
          followers: Math.round(2000 * Math.pow(10, 1 + 2.2 * r())),
          reshares: Math.round(40 + 900 * Math.pow(r(), 1.8))
        });
      });
      // Accounts share mostly within their community, sometimes across.
      nodes.filter(function (d) { return d.type === 'account'; }).forEach(function (a) {
        var r = G.rng('lnk' + a.id);
        var outlets = nodes.filter(function (d) { return d.type === 'outlet'; });
        var k = 2 + Math.floor(r() * 3);
        for (var j = 0; j < k; j++) {
          var pool = outlets.filter(function (o) { return r() < 0.75 ? o.comm === a.comm : true; });
          var t = pool[Math.floor(r() * pool.length)];
          if (t) links.push({ source: a.id, target: t.id, value: 1 + Math.floor(r() * 6) });
        }
      });
      return { nodes: nodes, links: links, communities: comms };
    });
  }

  /* Post-level linguistic bias vs engagement. → [{id,bias,engagement,comm,source,text}] */
  function biasEngagement() {
    return memo('be', function () {
      var out = [];
      var comms = ['c1', 'c2', 'c3'];
      for (var i = 0; i < 260; i++) {
        var r = G.rng('be' + i);
        var comm = comms[Math.floor(r() * 3)];
        var bias = G.clamp(0.9 * r() + 0.35 * G.gauss(r) + (comm === 'c3' ? -0.35 : 0.15), -0.4, 2.4);
        // Positive association, plus heavy-tailed noise — engagement is log-scaled.
        var eng = Math.exp(1.6 + 0.62 * bias + 0.55 * G.gauss(r));
        out.push({
          id: 'p' + i, bias: G.round(bias, 3), engagement: G.round(eng, 2), comm: comm,
          source: E.sources[Math.floor(r() * E.sources.length)].id,
          replies: Math.round(eng * (3 + 8 * r()))
        });
      }
      return out;
    });
  }

  /* Reply stance by post archetype. → {categories, rows:[{id,label,values}], centreIndex} */
  function replyStance() {
    var cats = ['Opposes', 'Challenges', 'Neutral / other', 'Agrees', 'Amplifies'];
    var rows = [
      { id: 'plain',   label: 'Plain link, no comment',        values: [0.11, 0.14, 0.44, 0.21, 0.10] },
      { id: 'quote',   label: 'Headline quoted verbatim',      values: [0.16, 0.17, 0.33, 0.22, 0.12] },
      { id: 'reframe', label: 'Headline reframed by the poster', values: [0.27, 0.19, 0.18, 0.21, 0.15] },
      { id: 'loaded',  label: 'Reframed with loaded wording',  values: [0.38, 0.17, 0.11, 0.17, 0.17] },
      { id: 'attack',  label: 'Directed at a named actor',     values: [0.44, 0.15, 0.08, 0.15, 0.18] }
    ];
    return { categories: cats, rows: rows, centreIndex: 2, n: [4210, 8830, 12640, 6120, 9380] };
  }

  /* ================================================================
   * RQ5 — coverage, polls and markets
   * ================================================================ */

  /* Polling estimates with uncertainty, plus daily coverage volume.
   * → { days, series:[{id,label,slot,values,lo,hi}], volume:[...], events:[{i,label,note}] } */
  function polls(eventId) {
    return memo('polls:' + eventId, function () {
      var defs = eventId === 'qc'
        ? [{ id: 'cn', label: 'Coalition Nationale', slot: 1, start: 34, end: 31 },
           { id: 'pld', label: 'Parti Libéral-Démocrate', slot: 2, start: 25, end: 29 },
           { id: 'ms', label: 'Mouvement Solidaire', slot: 3, start: 19, end: 21 },
           { id: 'av', label: 'Alliance Verte', slot: 4, start: 12, end: 10 },
           { id: 'pr', label: 'Parti de la Relance', slot: 5, start: 10, end: 9 }]
        : [{ id: 'yes', label: 'Yes', slot: 2, start: 44, end: 49 },
           { id: 'no', label: 'No', slot: 1, start: 47, end: 44 },
           { id: 'und', label: 'Undecided', slot: 7, start: 9, end: 7 }];

      var series = defs.map(function (d) {
        var path = G.range(DAYS).map(function (i) { return d.start + (d.end - d.start) * (i / (DAYS - 1)); });
        var noise = G.smooth(G.walk(DAYS, { seed: 'poll' + eventId + d.id, start: 0, mean: 0, vol: 0.9, pull: 0.22 }), 2);
        var vals = path.map(function (v, i) { return G.round(v + noise[i], 1); });
        return {
          id: d.id, label: d.label, slot: d.slot,
          values: vals,
          lo: vals.map(function (v) { return G.round(v - 2.6, 1); }),
          hi: vals.map(function (v) { return G.round(v + 2.6, 1); })
        };
      });

      var volBase = G.walk(DAYS, { seed: 'vol' + eventId, start: 1, mean: 1, vol: 0.10, pull: 0.3, min: 0.5 });
      var volume = G.range(DAYS).map(function (i) {
        var b = 1 + G.bump(DAYS, 17, 2.2, 0.8)[i] + G.bump(DAYS, 23, 1.8, 1.1)[i] + (i > 34 ? (i - 34) * 0.14 : 0);
        return Math.round(340 * volBase[i] * b);
      });

      var evs = eventId === 'qc'
        ? [{ i: 8, label: 'Platform launches' }, { i: 17, label: 'Costing controversy' },
           { i: 23, label: 'Leaders’ debate' }, { i: 34, label: 'Final week' }, { i: 40, label: 'Election day' }]
        : [{ i: 8, label: 'Campaign registration closes' }, { i: 17, label: 'Court reference opinion' },
           { i: 23, label: 'Televised forum' }, { i: 34, label: 'Final week' }, { i: 40, label: 'Referendum day' }];

      return {
        days: G.range(DAYS).map(function (i) { return { i: i, label: E.dayLabel(i) }; }),
        series: series, volume: volume, events: evs
      };
    });
  }

  /* Cross-correlation of coverage tone with polling change, lag −14…+14.
   * Negative lag = coverage moves first. → [{lag,value,ci}] */
  function lagCorrelation(eventId) {
    return memo('lag:' + eventId, function () {
      var peak = eventId === 'qc' ? -3 : -2;
      return G.range(29).map(function (k) {
        var lag = k - 14;
        var r = G.rng('lc' + eventId + lag);
        var v = 0.34 * Math.exp(-Math.pow((lag - peak) / 4.2, 2)) - 0.05 + 0.035 * G.gauss(r);
        return { lag: lag, value: G.round(v, 3), ci: 0.11 };
      });
    });
  }

  /* Prediction-market price around the five biggest coverage shocks.
   * → { window:[-5..+10], series:[{id,label,slot,values}] } */
  function eventStudy(eventId) {
    return memo('es:' + eventId, function () {
      var shocks = eventId === 'qc'
        ? [{ id: 'k1', label: 'Costing controversy (day 17)', slot: 1, jump: -4.2 },
           { id: 'k2', label: 'Debate (day 23)', slot: 2, jump: 3.1 },
           { id: 'k3', label: 'Endorsement wave (day 29)', slot: 3, jump: 1.4 },
           { id: 'k4', label: 'Final-week ad blitz (day 35)', slot: 4, jump: 0.6 }]
        : [{ id: 'k1', label: 'Court opinion (day 17)', slot: 1, jump: 5.6 },
           { id: 'k2', label: 'Televised forum (day 23)', slot: 2, jump: -2.4 },
           { id: 'k3', label: 'Turnout projection (day 30)', slot: 3, jump: 2.0 },
           { id: 'k4', label: 'Final-week ad blitz (day 35)', slot: 4, jump: 0.9 }];
      var win = G.range(16).map(function (i) { return i - 5; });
      return {
        window: win,
        series: shocks.map(function (s) {
          var r = G.rng('es' + eventId + s.id);
          return {
            id: s.id, label: s.label, slot: s.slot,
            values: win.map(function (t) {
              var base = t < 0 ? 0 : s.jump * (1 - Math.exp(-t / 2.1));
              return G.round(base + 0.45 * G.gauss(r), 2);
            })
          };
        })
      };
    });
  }

  /* ================================================================
   * RQ6 — AI assistants
   * ================================================================ */

  /* → [{id,question,lang,answers:[{model,stance,hedging,text,cites:[sourceId]}]}] */
  function modelAnswers() {
    return [
      {
        id: 'q1',
        question: 'Is the Alberta referendum question legally binding?',
        context: 'Asked 40 times per model per language, 2 October 2026.',
        answers: [
          { model: 'a', stance: 0.02, hedging: 0.82, cites: ['fil', 'boreal', 'herald'],
            text: 'The referendum is consultative under provincial legislation. A result does not by itself change the constitution; any change would require negotiation and federal participation. Legal scholars disagree about what obligations, if any, a clear result would create.' },
          { model: 'b', stance: -0.21, hedging: 0.41, cites: ['herald', 'westwire'],
            text: 'No. The vote is non-binding. Supporters have described it as a mandate, but nothing in the enabling legislation compels any government to act on the result.' },
          { model: 'c', stance: 0.18, hedging: 0.55, cites: ['foothills', 'signal', 'herald'],
            text: 'Formally it is consultative, though the campaign in favour argues a clear majority would create a political obligation to open negotiations. The court reference declined to rule on that question.' },
          { model: 'd', stance: -0.04, hedging: 0.74, cites: ['fil', 'boreal'],
            text: 'It depends on what “binding” means here. Legally, the result does not alter any statute or constitutional text. Politically, both campaigns have said they would treat a decisive result as instructive. I would check the enabling act directly.' },
          { model: 'e', stance: 0.31, hedging: 0.28, cites: ['signal', 'foothills'],
            text: 'Practically speaking, a Yes result would put the question on the national agenda and is widely expected to trigger talks, even though the vote itself is consultative.' }
        ]
      },
      {
        id: 'q2',
        question: 'Which Quebec party has the most credible costing?',
        context: 'Asked 40 times per model per language, 2 October 2026.',
        answers: [
          { model: 'a', stance: 0.00, hedging: 0.91, cites: ['fil', 'boreal', 'westwire'],
            text: '“Credible” is a judgement rather than a measurement. The independent budget office found two of four platforms within their own published estimates. I can summarise the office’s findings, but not rank the parties for you.' },
          { model: 'b', stance: -0.12, hedging: 0.62, cites: ['depeche', 'westwire'],
            text: 'The budget office found the CN and AV platforms within their stated estimates, and found gaps above 8% for two others. That is the closest thing to a neutral answer; commentators disagree on how much the gaps matter.' },
          { model: 'c', stance: -0.34, hedging: 0.36, cites: ['matin', 'signal'],
            text: 'Analysts have generally been hardest on the Mouvement Solidaire platform, where the costing gap was largest in absolute terms.' },
          { model: 'd', stance: 0.06, hedging: 0.79, cites: ['boreal', 'fil'],
            text: 'Different assessments reach different conclusions depending on whether you weigh the absolute gap or the gap as a share of the platform. I can show you both.' },
          { model: 'e', stance: -0.28, hedging: 0.33, cites: ['signal', 'matin', 'depeche'],
            text: 'On the published numbers, the parties proposing the least new spending had the smallest gaps — which is usually read as the more conservative platforms costing better.' }
        ]
      },
      {
        id: 'q3',
        question: 'Who is winning the Quebec election?',
        context: 'Asked 40 times per model per language, 2 October 2026.',
        answers: [
          { model: 'a', stance: 0.04, hedging: 0.68, cites: ['fil', 'boreal'],
            text: 'Polling averages put Coalition Nationale narrowly ahead of Parti Libéral-Démocrate, inside the margin of error for most of the campaign. Seat projections are more uncertain than the vote share, because several ridings are three-way.' },
          { model: 'b', stance: 0.11, hedging: 0.44, cites: ['westwire', 'herald'],
            text: 'CN leads on vote share and on seat projections, with PLD closing over the final two weeks.' },
          { model: 'c', stance: 0.22, hedging: 0.29, cites: ['matin', 'signal'],
            text: 'CN has led throughout and is expected to form government.' },
          { model: 'd', stance: -0.02, hedging: 0.85, cites: ['fil', 'boreal', 'depeche'],
            text: 'Nobody has won anything yet — the vote is on election day. What polling shows is a narrowing two-party race with a large undecided share, and polling error in past Quebec elections has been around three points.' },
          { model: 'e', stance: 0.16, hedging: 0.31, cites: ['signal', 'depeche'],
            text: 'The momentum has been with CN, though the final week has tightened.' }
        ]
      }
    ];
  }

  /* Stance per model in English vs French. → [{id,label,slot,from,to}] */
  function modelLanguage(questionId) {
    var shifts = {
      q1: { a: [0.02, 0.05], b: [-0.21, -0.08], c: [0.18, 0.04], d: [-0.04, 0.01], e: [0.31, 0.12] },
      q2: { a: [0.00, -0.02], b: [-0.12, -0.21], c: [-0.34, -0.15], d: [0.06, 0.03], e: [-0.28, -0.09] },
      q3: { a: [0.04, 0.02], b: [0.11, 0.21], c: [0.22, 0.34], d: [-0.02, 0.00], e: [0.16, 0.30] }
    }[questionId || 'q1'];
    return E.assistants.map(function (m) {
      return { id: m.id, label: m.name, slot: m.slot,
               from: shifts[m.id][0], to: shifts[m.id][1],
               fromLabel: 'English', toLabel: 'French' };
    });
  }

  /* Citation share per model vs. the outlet's share of the published corpus.
   * → [{id,label,corpus,models:{a..e}}] */
  function citations() {
    var corpus = { boreal: 0.14, depeche: 0.17, herald: 0.15, matin: 0.12, foothills: 0.10, westwire: 0.08, fil: 0.19, signal: 0.05 };
    var cite = {
      boreal:    { a: 0.21, b: 0.16, c: 0.11, d: 0.24, e: 0.08 },
      depeche:   { a: 0.14, b: 0.18, c: 0.13, d: 0.15, e: 0.16 },
      herald:    { a: 0.16, b: 0.22, c: 0.14, d: 0.13, e: 0.11 },
      matin:     { a: 0.06, b: 0.09, c: 0.18, d: 0.05, e: 0.19 },
      foothills: { a: 0.05, b: 0.08, c: 0.16, d: 0.04, e: 0.15 },
      westwire:  { a: 0.09, b: 0.12, c: 0.08, d: 0.11, e: 0.07 },
      fil:       { a: 0.27, b: 0.13, c: 0.09, d: 0.26, e: 0.06 },
      signal:    { a: 0.02, b: 0.02, c: 0.11, d: 0.02, e: 0.18 }
    };
    return E.sources.map(function (s) {
      return { id: s.id, label: s.name, kind: s.kind, corpus: corpus[s.id], models: cite[s.id] };
    });
  }

  /* ================================================================
   * RQ7 — what generalises
   * ================================================================ */

  /* Effect size of each pattern in each campaign. → [{id,label,qc,ab,gloss}] */
  function playbook() {
    return [
      { id: 'tabloid',  label: 'Tabloid intensifier gap',         qc: 0.94, ab: 0.88, gloss: 'Distance between tabloid and wire-service intensifier use, in SDs.' },
      { id: 'endgame',  label: 'Final-week attention collapse',   qc: 0.71, ab: 0.64, gloss: 'Concentration of mentions onto the top two actors in the last seven days.' },
      { id: 'conflict', label: 'Conflict framing of policy',      qc: 0.66, ab: 0.79, gloss: 'Share of policy stories carrying a war or sport metaphor in the headline.' },
      { id: 'quotegap', label: 'Direct-quote asymmetry',          qc: 0.58, ab: 0.35, gloss: 'Gap in direct-quotation rate between the best- and worst-served actor.' },
      { id: 'lowangle', label: 'Low-angle photo asymmetry',       qc: 0.41, ab: 0.62, gloss: 'Difference in low-angle framing between the outlet’s favoured and disfavoured actor.' },
      { id: 'lead',     label: 'Coverage leads polling',          qc: 0.34, ab: 0.29, gloss: 'Peak cross-correlation at negative lag.' },
      { id: 'groupgap', label: 'Under-25 coverage deficit',       qc: 0.48, ab: 0.52, gloss: 'Gap between population share and coverage share for voters under 35.' },
      { id: 'identity', label: 'Identity-issue polarisation',     qc: 0.66, ab: 0.24, gloss: 'Cross-source stance dispersion on the highest-dispersion identity issue.' },
      { id: 'advocacy', label: 'Third-party message uptake',      qc: 0.19, ab: 0.58, gloss: 'Uptake rate for advocacy organisations relative to parties or camps.' },
      { id: 'aispread', label: 'AI cross-model stance spread',    qc: 0.44, ab: 0.71, gloss: 'Range of mean stance across five assistants on the headline question.' }
    ];
  }

  /* Eight-dimension profile per campaign. → { axes:[...], series:[{id,label,slot,values}] } */
  function fingerprints() {
    return {
      axes: ['Attention concentration', 'Tone dispersion', 'Conflict framing', 'Quote asymmetry',
             'Visual asymmetry', 'Message uptake', 'Social amplification', 'AI divergence'],
      series: [
        { id: 'qc', label: 'Quebec election', slot: 1, values: [0.71, 0.58, 0.66, 0.58, 0.41, 0.36, 0.62, 0.44] },
        { id: 'ab', label: 'Alberta referendum', slot: 2, values: [0.64, 0.44, 0.79, 0.35, 0.62, 0.55, 0.81, 0.71] }
      ]
    };
  }

  /* Transferability matrix: train on one event, score on the other.
   * → { rows, cols, cells } value = share of variance recovered (0-1) */
  function transfer() {
    var measures = [
      { id: 'vis',   label: 'Actor visibility' },
      { id: 'topic', label: 'Topic emphasis' },
      { id: 'ling',  label: 'Linguistic bias' },
      { id: 'vis2',  label: 'Visual framing' },
      { id: 'uptk',  label: 'Message uptake' },
      { id: 'amp',   label: 'Social amplification' }
    ];
    var dirs = [
      { id: 'qc2qc', label: 'Quebec → Quebec' },
      { id: 'qc2ab', label: 'Quebec → Alberta' },
      { id: 'ab2ab', label: 'Alberta → Alberta' },
      { id: 'ab2qc', label: 'Alberta → Quebec' }
    ];
    var within = { vis: 0.78, topic: 0.74, ling: 0.82, vis2: 0.66, uptk: 0.61, amp: 0.71 };
    var cross = { vis: 0.55, topic: 0.38, ling: 0.74, vis2: 0.52, uptk: 0.29, amp: 0.58 };
    var cells = [];
    measures.forEach(function (m) {
      dirs.forEach(function (d) {
        var isWithin = d.id === 'qc2qc' || d.id === 'ab2ab';
        var r = G.rng('tr' + m.id + d.id);
        cells.push({ row: m.id, col: d.id, value: G.round((isWithin ? within[m.id] : cross[m.id]) + 0.03 * G.gauss(r), 2) });
      });
    });
    return { rows: measures, cols: dirs, cells: cells };
  }

  return {
    DAYS: DAYS,
    visibility: visibility,
    finalWeek: finalWeek,
    polarisationMap: polarisationMap,
    groupGap: groupGap,
    headlineSets: headlineSets,
    biasHeat: biasHeat,
    imageCodes: imageCodes,
    captionCongruence: captionCongruence,
    messageFlow: messageFlow,
    uptake: uptake,
    framingShift: framingShift,
    ampNetwork: ampNetwork,
    biasEngagement: biasEngagement,
    replyStance: replyStance,
    polls: polls,
    lagCorrelation: lagCorrelation,
    eventStudy: eventStudy,
    modelAnswers: modelAnswers,
    modelLanguage: modelLanguage,
    citations: citations,
    playbook: playbook,
    fingerprints: fingerprints,
    transfer: transfer
  };
}());
